
name: test_flow

on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
    
  pyright:
    runs-on: ubuntu-latest
    needs: ruff  # run after ruff
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.10'
          cache: true
      - name: Install dependencies
        run: pdm install --dev
      - name: Add bin to PATH
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH  # required for pyright
      - name: Run pyright
        uses: jakebailey/pyright-action@v2

  test:
    runs-on: ${{ matrix.os }}
    needs: [ruff, pyright]    # run after lint & type checking
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.10'
          cache: true
      - name: Install dependencies
        run: pdm install --dev
      - name: Run Tests
        run: |
          pdm run -v pytest tests
